In [1]:
import os
import numpy as np
import pandas as pd

In [3]:
path_household_deprivation = 'https://github.com/cabbagejiejiejie/QM_Assessment/blob/main/data/Household%20deprivation.xlsx?raw=true'
sheet_name = '2021'

df_household_deprivation = pd.read_excel(path_household_deprivation, sheet_name=sheet_name, engine='openpyxl')

In [4]:
df_household_deprivation

,ward code,ward name,local authority code,local authority name,All Households,deprived in: no dimensions,1 dimension,2 dimensions,3 dimensions,4 dimensions
0,E09000001,City of London (aggregated),E09000001,City of London,4909,2937,1547,343,75,7
1,E05014053,Abbey,E09000002,Barking and Dagenham,1460,604,568,221,62,5
2,E05014054,Alibon,E09000002,Barking and Dagenham,3344,1302,1246,612,173,11
3,E05014055,Barking Riverside,E09000002,Barking and Dagenham,3382,1591,1120,500,158,13
4,E05014056,Beam,E09000002,Barking and Dagenham,2705,1058,1026,488,125,8
...,...,...,...,...,...,...,...,...,...,...
675,E05013805,Regent's Park,E09000033,Westminster,5663,3268,1649,564,158,24
676,E05013806,St James's,E09000033,Westminster,5169,2923,1485,557,166,38
677,E05013807,Vincent Square,E09000033,Westminster,5167,2547,1565,748,265,42
678,E05013808,West End,E09000033,Westminster,6076,3262,1912,662,196,44
679,E05013809,Westbourne,E09000033,Westminster,4686,1626,1511,1038,447,64

In [29]:
grouped = df_household_deprivation.groupby('local authority name')

list_split_dfs = []

for group_name, group_df in grouped:
    list_split_dfs.append(group_df.reset_index(drop=True))

In [39]:
for dfs in list_split_dfs:
    sum_row = dfs.sum()
    dfs.loc['total'] = sum_row
    dfs['poor_household'] = dfs['1 dimension']/dfs['All Households']
    dfs.at['total', 'ward code'] = ''
    dfs.at['total', 'ward name'] = ''
    dfs.at['total', 'local authority code'] = dfs.at[0, 'local authority code']
    dfs.at['total', 'local authority name'] = dfs.at[0, 'local authority name']

In [40]:
dfs = list_split_dfs[10]
dfs

,ward code,ward name,local authority code,local authority name,All Households,deprived in: no dimensions,1 dimension,2 dimensions,3 dimensions,4 dimensions,poor_household
0,E05014072,Abbey Wood,E09000011,Greenwich,6207,2432,2239,1116,374,46,0.360722
1,E05014073,Blackheath Westcombe,E09000011,Greenwich,6769,3909,1891,752,203,14,0.279362
2,E05014074,Charlton Hornfair,E09000011,Greenwich,4622,2275,1396,693,245,13,0.302034
3,E05014075,Charlton Village & Riverside,E09000011,Greenwich,3969,1666,1355,688,245,15,0.341396
4,E05014076,East Greenwich,E09000011,Greenwich,6391,3743,1752,669,208,19,0.274136
5,E05014077,Eltham Page,E09000011,Greenwich,3503,1358,1215,679,239,12,0.346846
6,E05014078,Eltham Park & Progress,E09000011,Greenwich,4120,2144,1334,529,112,1,0.323786
7,E05014079,Eltham Town & Avery Hill,E09000011,Greenwich,6281,3049,2056,922,234,20,0.327336
8,E05014080,Greenwich Creekside,E09000011,Greenwich,4857,2982,1231,467,164,13,0.253449
9,E05014081,Greenwich Park,E09000011,Greenwich,4540,2632,1298,472,124,14,0.285903
10,E05014082,Greenwich Peninsula,E09000011,Greenwich,5067,3286,1283,380,111,7,0.253207
11,E05014083,Kidbrooke Park,E09000011,Greenwich,3960,1829,1302,601,208,20,0.328788
12,E05014084,Kidbrooke Village & Sutcliffe,E09000011,Greenwich,2696,1601,729,276,90,0,0.270401
13,E05014085,Middle Park & Horn Park,E09000011,Greenwich,3542,1366,1194,696,277,9,0.337098
14,E05014086,"Mottingham, Coldharbour & New Eltham",E09000011,Greenwich,5666,2750,1799,854,246,17,0.317508
15,E05014087,Plumstead & Glyndon,E09000011,Greenwich,7520,2798,2692,1442,542,46,0.357979
16,E05014088,Plumstead Common,E09000011,Greenwich,6011,2616,2096,949,324,26,0.348694
17,E05014089,Shooters Hill,E09000011,Greenwich,4732,2180,1621,698,202,31,0.342561
18,E05014090,Thamesmead Moorings,E09000011,Greenwich,4605,1762,1741,809,263,30,0.378067
19,E05014091,West Thamesmead,E09000011,Greenwich,3926,1741,1379,581,207,18,0.351248
20,E05014092,Woolwich Arsenal,E09000011,Greenwich,5774,3276,1697,608,184,9,0.293904
21,E05014093,Woolwich Common,E09000011,Greenwich,4862,1984,1677,884,288,29,0.344920
22,E05014094,Woolwich Dockyard,E09000011,Greenwich,4472,1628,1670,841,314,19,0.373435
total,,,E09000011,Greenwich,342276,165021,109941,49818,16212,1284,0.321206